apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-user-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: PLACEHOLDER_PATH  # overridden via patch
    repoURL: https://github.com/heymikeey/gitops-lab.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
